default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  username: postgres
  password: postgres
  database: api_development

test:
  <<: *default
  username: postgres
  password: postgres
  databse: api_test


production:
  <<: *default